// maplibre-geoman-angular/src/app/components/geoman-map/geoman-map.component.ts

import { Component, ElementRef, EventEmitter, OnInit, Output, ViewChild } from '@angular/core';

import { Geoman, GmOptionsPartial } from '@geoman-io/maplibre-geoman-free';
import * as ml from 'maplibre-gl';

import { demoFeatures } from '../../fixtures/features';
import mapStyle from './style';

@Component({
    selector: 'app-geoman-map',
    imports: [],
    templateUrl: './geoman-map.component.html',
    styleUrls: ['./geoman-map.component.scss']
})
export class GeomanMapComponent implements OnInit {
  @ViewChild('mapElement', { static: true }) mapElement!: ElementRef<HTMLDivElement>;
  @Output() gmEvent = new EventEmitter<any>();

  ngOnInit() {
    if (!this.mapElement) {
      console.warn('Missing map element');
      return;
    }

    // Create MapLibre map
    const map = new ml.Map({
      container: this.mapElement.nativeElement,
      style: mapStyle,
      center: [0, 51],
      zoom: 5,
    });

    // Define Geoman options
    const gmOptions: GmOptionsPartial = {
      controls: {
        edit: {
          drag: { uiEnabled: true },
          change: { uiEnabled: true },
        },
      },
    };

    // Instantiate Geoman
    const geoman = new Geoman(map, gmOptions);

    // Load some demo shapes
    const loadDevShapes = () => {
      demoFeatures.forEach(shapeGeoJson => {
        geoman.features.addGeoJsonFeature({
          shapeGeoJson,
          defaultSource: true,
        });
      });
      console.log('Shapes loaded', demoFeatures);
    };

    // Wait for geoman ready
    map.on('gm:loaded', () => {
      console.log('Geoman fully loaded');
      loadDevShapes();

      // Enable a default draw tool
      geoman.enableDraw('line');
    });

    // Listen for all relevant Geoman events
    map.on('gm:globaldrawmodetoggled', e => this.gmEvent.emit(e));
    map.on('gm:globaleditmodetoggled', e => this.gmEvent.emit(e));
    map.on('gm:globalremovemodetoggled', e => this.gmEvent.emit(e));
    map.on('gm:globalrotatemodetoggled', e => this.gmEvent.emit(e));
    map.on('gm:globaldragmodetoggled', e => this.gmEvent.emit(e));
    map.on('gm:globalcutmodetoggled', e => this.gmEvent.emit(e));
    map.on('gm:globalsnappingmodetoggled', e => this.gmEvent.emit(e));

    // Create events
    map.on('gm:create', e => this.gmEvent.emit(e));

    // Edit events
    map.on('gm:editstart', e => this.gmEvent.emit(e));
    map.on('gm:editend', e => this.gmEvent.emit(e));

    // Remove events
    map.on('gm:remove', e => this.gmEvent.emit(e));

    // Rotate events
    map.on('gm:rotatestart', e => this.gmEvent.emit(e));
    map.on('gm:rotateend', e => this.gmEvent.emit(e));

    // Drag events
    map.on('gm:dragstart', e => this.gmEvent.emit(e));
    map.on('gm:dragend', e => this.gmEvent.emit(e));

    // Cut events
    map.on('gm:cut', e => this.gmEvent.emit(e));

    // Helper & control
    map.on('gm:helper', e => this.gmEvent.emit(e));
    map.on('gm:control', e => this.gmEvent.emit(e));
  }
}

<div class="geoman-map" #mapElement></div>

// maplibre-geoman-vue/src/components/map/GeomanMap.vue
<template>
  <div class="geoman-map" ref="mapElement"></div>
</template>

<script setup lang="ts">
import { GeoJsonImportFeature, Geoman, GmOptionsPartial } from '@geoman-io/maplibre-geoman-free';
import { demoFeatures } from '@/fixtures/features.ts';
import ml from 'maplibre-gl';

import '@geoman-io/maplibre-geoman-free/dist/maplibre-geoman.css';
import 'maplibre-gl/dist/maplibre-gl.css';
import { onMounted, ref } from 'vue';
import mapStyle from './style';


const emit = defineEmits(['gm-event']);
const mapElement = ref<HTMLElement | null>(null);

onMounted(() => {
  if (!mapElement.value) {
    console.log('Missing map element');
    return;
  }

  const map = new ml.Map({
    container: mapElement.value,
    style: mapStyle,
    center: [0, 51],
    zoom: 5,
  });


  const gmOptions: GmOptionsPartial = {
    settings: {
      eventPrefix: 'gm',
    },
    // geoman options here
    controls: {
      edit: {
        drag: {
          uiEnabled: true,
        },
        edit: {
          uiEnabled: true,
        }
      },
    }
  };

  // create a new geoman instance
  const geoman = new Geoman(map, gmOptions);

  const loadDevShapes = () => {
    if (!geoman) {
      console.warn('Geoman not loaded yet');
      return;
    }

    const gm = geoman;

    demoFeatures.forEach((shapeGeoJson) => {
      gm.features.addGeoJsonFeature({ shapeGeoJson });
    });

    console.log('Shapes loaded', demoFeatures);
  };

  // Enable to listen to all events
  //   map.gm.setGlobalEventsListener((event: GlobalEventsListenerParemeters) => {
  //   if (event.type === 'converted') {
  //     console.log('Regular event', event);
  //   } else if (event.type === 'system') {
  //     console.log('System event', event);
  //   }
  // });

  // enable drawing tools
  geoman.enableDraw('line');

  // load shapes
  map.on('gm:loaded', () => {
    console.log('Geoman fully loaded');

    // Here we can define and add a geojson shape to the map (or load it from a server)
    loadDevShapes();
  });

  // Mode events
  map.on('gm:globaldrawmodetoggled', (event) => emit('gm-event', event));
  map.on('gm:globaleditmodetoggled', (event) => emit('gm-event', event));
  map.on('gm:globalremovemodetoggled', (event) => emit('gm-event', event));
  map.on('gm:globalrotatemodetoggled', (event) => emit('gm-event', event));
  map.on('gm:globaldragmodetoggled', (event) => emit('gm-event', event));
  map.on('gm:globalcutmodetoggled', (event) => emit('gm-event', event));
  map.on('gm:globalsnappingmodetoggled', (event) => emit('gm-event', event));

  // Drawing events
  //map.on('gm:draw', (event) => emit('gm-event', event)); // Enable to listen to all draw events
  map.on('gm:create', (event) => emit('gm-event', event));

  // Edit events
  //map.on('gm:edit', (event) => emit('gm-event', event)); // Enable to listen to all edit events
  map.on('gm:editstart', (event) => emit('gm-event', event));
  map.on('gm:editend', (event) => emit('gm-event', event));

  // Remove events
  map.on('gm:remove', (event) => emit('gm-event', event));

  // Rotate events
  //map.on('gm:rotate', (event) => emit('gm-event', event)); // Enable to listen to all rotate events
  map.on('gm:rotatestart', (event) => emit('gm-event', event));
  map.on('gm:rotateend', (event) => emit('gm-event', event));


  // Drag events
  //map.on('gm:drag', (event) => emit('gm-event', event)); // Enable to listen to all drag events
  map.on('gm:dragstart', (event) => emit('gm-event', event));
  map.on('gm:dragend', (event) => emit('gm-event', event));

  // Cut events
  map.on('gm:cut', (event) => emit('gm-event', event));

  // Enable to listen to all helper and control events
  map.on('gm:helper', (event) => emit('gm-event', event));
  map.on('gm:control', (event) => emit('gm-event', event));
});
</script>

<style scoped lang="scss">
.geoman-map {
  background-color: #f7f7f7;
}
</style>
