// maplibre-geoman-nextjs/src/app/page.tsx
'use client';

import GmMap from '@/components/GmMap';
import Sidebar from '@/components/Sidebar';
import type { GmEvent, GmEventData } from '@/types/events';
import type { FeatureData } from '@geoman-io/maplibre-geoman-free';
import React, { useCallback, useState } from 'react';
import '@/styles/index.css';


const Page: React.FC = () => {
  const [gmEvents, setGmEvents] = useState<GmEventData[]>([]);

  const getGeoJson = useCallback((featureData: FeatureData) => {
    try {
      return JSON.stringify(featureData.getGeoJson(), null, 2);
    } catch (error) {
      return `Can't retrieve GeoJSON: ${error}`;
    }
  }, []);

  const handleEvent = useCallback(
    (event: GmEvent) => {
      console.log('Event', event);

      setGmEvents((prevEvents) => [
        ...prevEvents,
        {
          id: event.feature?.id,
          enabled: event.enabled,
          timestamp: new Date().toLocaleTimeString(),
          type: event.type,
          shape: event.shape,
          geojson: event.feature ? getGeoJson(event.feature) : undefined,
        },
      ]);
    },
    [getGeoJson]
  );

  return (
    <main className="main-container">
      <GmMap handleEvent={handleEvent} />
      <Sidebar gmEvents={gmEvents} />
    </main>
  );
};

export default Page;

// maplibre-geoman-svelte/src/App.svelte
<script lang="ts">
  import './styles/index.css';
  import GmMap from './components/GmMap.svelte';
  import Sidebar from './components/Sidebar.svelte';


  const gmEvents: Array<any> = $state([]);

  const getGeoJson = (featureData: any) => {
    try {
      return JSON.stringify(featureData.getGeoJson(), null, 2);
    } catch (e) {
      return 'Can\'t retrieve GeoJSON';
    }
  };

  const handleEvent = (event: any) => {
    console.log('Event', event);

    gmEvents.push({
      id: event?.feature?.id ?? undefined,
      enabled: event?.enabled ?? undefined,
      timestamp: new Date().toLocaleTimeString(),
      type: event?.type,
      shape: event?.shape ?? undefined,
      geojson: event?.feature ? getGeoJson(event.feature) : undefined,
    });
  };
</script>

<main class="main-container">
  <GmMap {handleEvent} />
  <Sidebar {gmEvents} />
</main>

<style>
  .main-container {
    margin: 0;
    padding: 0;
    display: flex;
    height: 100vh;
    width: 100vw;
  }
</style>
