// maplibre-geoman-vue/src/App.vue
<template>
  <div class="main-container">
    <GeomanMap class="map" @gm-event="handleGmEvent" />
    <Sidebar :gmEvents="gmEvents" class="sidebar" />
  </div>
</template>

<script lang="ts">
import { defineComponent, type Raw } from 'vue';
import GeomanMap from '@/components/map/GeomanMap.vue';
import Sidebar from '@/components/Sidebar.vue';


type ComponentData = {
  gmEvents: Array<Raw<any>>;

};

export default defineComponent({
  components: {
    GeomanMap,
    Sidebar,
  },

  data(): ComponentData {
    return {
      gmEvents: [] as Array<any>,
    };
  },

  methods: {
    getGeoJson(featureData: any) {
      try {
        return JSON.stringify(featureData.getGeoJson(), null, 2);
      } catch (e) {
        return 'Can\'t retrieve GeoJSON';
      }
    },

    handleGmEvent(event: any) {
      console.log(event);
      this.gmEvents.push({
        id: event.feature?.id ?? undefined,
        enabled: event.enabled ?? undefined,
        timestamp: new Date().toLocaleTimeString(),
        type: event.type,
        shape: event.shape ?? undefined,
        geojson: event.feature ? this.getGeoJson(event.feature) : undefined,
      });
    },
  },
});
</script>

<style lang="scss" scoped>
.main-container {
  margin: 0;
  padding: 0;
  display: flex;
  height: 100vh;
  width: 100vw;

  .map {
    width: 5rem;
    flex: 1 1 auto;
  }

  .sidebar {
    width: 25rem;
    flex: 0 0 auto;
  }
}
</style>

// maplibre-geoman-angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { FormsModule } from '@angular/forms';

import { SidebarComponent } from './components/sidebar/sidebar.component';
import { GeomanMapComponent } from './components/geoman-map/geoman-map.component';

interface GmEvent {
  id?: string;
  enabled?: boolean;
  timestamp?: string;
  type?: string;
  shape?: string;
  geojson?: any;
}

@Component({
    selector: 'app-root',
    imports: [
    FormsModule,
    SidebarComponent,
    GeomanMapComponent
],
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
  gmEvents: GmEvent[] = [];

  handleGmEvent(event: any) {
    console.log(event);
    this.gmEvents.push({
      id: event.feature?.id ?? undefined,
      enabled: event.enabled ?? undefined,
      timestamp: new Date().toLocaleTimeString(),
      type: event.type,
      shape: event.shape ?? undefined,
      geojson: event.feature ? this.getGeoJson(event.feature) : undefined,
    });
  }

  getGeoJson(featureData: any) {
    try {
      return JSON.stringify(featureData.getGeoJson(), null, 2);
    } catch (e) {
      return "Can't retrieve GeoJSON";
    }
  }
}

<div class="main-container">
  <app-geoman-map class="map" (gmEvent)="handleGmEvent($event)"></app-geoman-map>
  <app-sidebar [gmEvents]="gmEvents" class="sidebar"></app-sidebar>
</div>
