// maplibre-geoman-react/src/components/Sidebar.tsx
import React, { useEffect, useRef, useState } from 'react';
import type { GmEventData } from '../types.ts';


interface SidebarProps {
  gmEvents: GmEventData[];
}

const Sidebar: React.FC<SidebarProps> = ({ gmEvents }) => {
  const [expandedGeojsonItem, setExpandedGeojsonItem] = useState<number>(-1);
  const sidebarElement = useRef<HTMLDivElement>(null);

  const toggleGeoJsonItem = (index: number) => {
    setExpandedGeojsonItem((prevIndex) => (prevIndex === index ? -1 : index));
  };

  useEffect(() => {
    if (sidebarElement.current) {
      sidebarElement.current.scrollTo(0, sidebarElement.current.scrollHeight);
    }
  }, [gmEvents.length]);

  return (
    <div className="sidebar" ref={sidebarElement}>
      {gmEvents.map((item, index) => (
        <div className="event-item" key={index}>
          <div>[{item.timestamp}]</div>
          <div>EventType: {item.type}</div>

          {item.type === 'gm:globaldrawmodetoggled' && (
            <>
              <div>Shape: {item.shape}</div>
              <div>Enabled: {item.enabled}</div>
            </>
          )}

          {[
            'gm:globalsnappingmodetoggled',
            'gm:globalcutmodetoggled',
            'gm:globaleditmodetoggled',
            'gm:globaldragmodetoggled',
            'gm:globalrotatemodetoggled',
          ].includes(item.type) && (
            <div>Enabled: {item.enabled}</div>
          )}

          {item.type === 'gm:create' && (
            <>
              <div>Feature Id: {item.id}</div>
              <div>Feature type: {item.shape}</div>
              <button
                className="geojson-header"
                onClick={() => toggleGeoJsonItem(index)}
              >
                GeoJSON
              </button>
              {expandedGeojsonItem === index && (
                <pre className="geojson">{item.geojson}</pre>
              )}
            </>
          )}

          {item.type === 'gm:remove' && (
            <>
              <div>Feature Id: {item.id}</div>
              <div>Feature type: {item.shape}</div>
            </>
          )}

          {[
            'gm:drag',
            'gm:dragstart',
            'gm:dragend',
            'gm:edit',
            'gm:editstart',
            'gm:editend',
            'gm:scale',
            'gm:scalestart',
            'gm:scaleend',
            'gm:rotate',
            'gm:rotatestart',
            'gm:rotateend',
            'gm:cut',
          ].includes(item.type) && (
            <>
              <div>Feature Id: {item.id}</div>
              <button
                className="geojson-header"
                onClick={() => toggleGeoJsonItem(index)}
              >
                GeoJSON
              </button>
              {expandedGeojsonItem === index && (
                <pre className="geojson">{item.geojson}</pre>
              )}
            </>
          )}
        </div>
      ))}
    </div>
  );
};

export default Sidebar;

// maplibre-geoman-angular/src/app/components/sidebar/sidebar.component.ts
import {
  Component,
  Input,
  OnChanges,
  SimpleChanges,
  ViewChild,
  ElementRef
} from '@angular/core';


interface GmEvent {
  id?: string;
  enabled?: boolean;
  timestamp?: string;
  type?: string;
  shape?: string;
  geojson?: string;
}

@Component({
    selector: 'app-sidebar',
    imports: [],
    templateUrl: './sidebar.component.html',
    styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent implements OnChanges {
  @Input() gmEvents: GmEvent[] = [];
  @ViewChild('sidebarElement', { static: true })
  sidebarElement!: ElementRef<HTMLDivElement>;

  expandedGeojsonItem = -1;
  expandedFeatureId = '';

  constructor(hostEl: ElementRef<HTMLDivElement>) {
    this.sidebarElement = hostEl;
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['gmEvents'] && this.sidebarElement) {
      setTimeout(() => {
        this.sidebarElement.nativeElement.scrollTop =
          this.sidebarElement.nativeElement.scrollHeight;
      });
    }
  }

  toggleGeoJsonItem(index: number) {
    this.expandedGeojsonItem =
      (this.expandedGeojsonItem === index) ? -1 : index;
  }

  toggleFeatureGeoJson(id: string) {
    this.expandedFeatureId =
      (this.expandedFeatureId === id) ? '' : id;
  }
}

@for (item of gmEvents; track item; let index = $index) {
  <div
    class="event-item"
    [attr.data-index]="index"
    >
    <div>[{{ item.timestamp }}]</div>
    <div>EventType: {{ item.type }}</div>
    <!-- gm:globaldrawmodetoggled -->
    @if (item.type === 'gm:globaldrawmodetoggled') {
      <div>Shape: {{ item.shape }}</div>
      <div>Enabled: {{ item.enabled }}</div>
    }
    <!-- Toggling events -->
    @if (
      item.type === 'gm:globalsnappingmodetoggled' ||
      item.type === 'gm:globalcutmodetoggled' ||
      item.type === 'gm:globaleditmodetoggled' ||
      item.type === 'gm:globaldragmodetoggled' ||
      item.type === 'gm:globalrotatemodetoggled'
      ) {
      <div>Enabled: {{ item.enabled }}</div>
    }
    <!-- Create event -->
    @if (item.type === 'gm:create') {
      <div>Feature Id: {{ item.id }}</div>
      <div>Feature type: {{ item.shape }}</div>
      <div class="geojson-header" (click)="toggleGeoJsonItem(index)">GeoJSON</div>
      @if (expandedGeojsonItem === index) {
        <pre class="geojson">
          {{ item.geojson }}
        </pre>
      }
    }
    <!-- Remove event -->
    @if (item.type === 'gm:remove') {
      <div>Feature Id: {{ item.id }}</div>
      <div>Feature type: {{ item.shape }}</div>
    }
    <!-- Drag, edit, scale, rotate, cut events -->
    @if (
      item.type === 'gm:drag' ||
      item.type === 'gm:dragend' ||
      item.type === 'gm:editend' ||
      item.type === 'gm:scaleend' ||
      item.type === 'gm:rotateend' ||
      item.type === 'gm:cut'
      ) {
      <div>Feature Id: {{ item.id }}</div>
      <div class="geojson-header" (click)="toggleGeoJsonItem(index)">GeoJSON</div>
      @if (expandedGeojsonItem === index) {
        <pre class="geojson">
          {{ item.geojson }}
        </pre>
      }
    }
  </div>
}
